# Generated by Django 4.0.4 on 2022-05-28 14:38

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0003_homepage_banner_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'hellow world', 'verbose_name_plural': 'hello worlds '},
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_page_banner_image', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_subtitl',
            field=wagtail.fields.RichTextField(default='Test Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='bannerr_cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_page_banner_cta', to='wagtailcore.page'),
        ),
    ]
