# Generated by Django 4.0.4 on 2022-05-29 18:04

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_options_homepage_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('cta', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add a title', max_length=100, required=True)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('button_page', wagtail.blocks.PageChooserBlock(required=False)), ('button_text', wagtail.blocks.CharBlock(default='Learn More', max_length=40, required=True)), ('button_url', wagtail.blocks.URLBlock(help_text='Button will link to this URL', required=False))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
